name: scribe-data-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black>=19.10b0
  - defusedxml=0.7.1
  - pytest-cov>=3.0.0
  - sentencepiece>=0.1.95
  - tabulate>=0.8.9
  - transformers>=4.12
  - tqdm=4.59.0
  - pip:
      - beautifulsoup4==4.9.3
      - mwparserfromhell==0.6
      - python-dateutil>=2.8.2
      - SPARQLWrapper>=2.0.0
      - tensorflow>=2.5.1
