name: scribe-data-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black>=19.10b0
  - sentencepiece>=0.1.95
  - tabulate>=0.8.9
  - transformers>=4.12
  - pip:
      - python-dateutil>=2.8.2
      - SPARQLWrapper>=2.0.0
