name: scribe-data-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - beautifulsoup4>=4.12.0
  - defusedxml=0.7.1
  - pandas>=2.0.3
  - pytest-cov>=4.0.0
  - sentencepiece>=0.1.99
  - tabulate>=0.8.10
  - transformers>=4.24.0
  - tqdm=4.65.0
  - pip:
      - black>=23.7.0
      - emoji>=2.8.0
      - mwparserfromhell>=0.6.5
      - PyICU>=2.10.2 # Make sure to fulfill PyICU dependencies, see https://gitlab.pyicu.org/main/pyicu#installing-pyicu
      - python-dateutil>=2.8.2
      - regex>=2023.8.8
      - SPARQLWrapper>=2.0.0
      - langcodes>=3.0.0
      - language_data>=1.0.0
