blank_issues_enabled: false
contact_links:
  - name: ❓ Questions and everything else
    url: https://github.com/scribe-org/Scribe-Data/discussions
    about: Join us in the Scribe-Data community Discussions!
